# This is a basic workflow to help you get started with Actions

name: Publish Werkflow-AWS to PyPi

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
        - werkflow-aws/pyproject.toml
  pull_request:
    branches: [ main ]
    paths:
        - werkflow-aws/pyproject.toml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish_to_pypi:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: '3.13'
    - name: Build a binary wheel
      run: >-
        python -m
        pip install wheel build setuptools twine && \
        cd werkflow-aws && python -m build && \
        twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}